### PR TITLE
fix: allow script to be nested inside svelte:head

### PR DESCRIPTION
**Pull request by elianiva**
without this PR, this would break because HTML parser doesn't allow `script` or `style` tag to be nested inside another tag but in Svelte we can do that by placing them inside `svelte:head`

```svelte
<svelte:head>
  <script>console.log("Hello World!")</script>
</svelte:head>
```

### CODE REVIEW

**Comment by elianiva** [comment]
ping @Himujjal :]

**Comment by Himujjal** [comment]
I will have a look into it tomorrow. Didnt think this case would pop out.

**Comment by elianiva** [comment]
Also added the ability to nest script tag inside a block statement. I recently have this on my website and it broke without this PR. (I'll add the tests in a few minutes)

```svelte
{#if $theme === "dark"}
  <script
    src="https://utteranc.es/client.js"
    repo="elianiva/elianiva.me"
    issue-term="pathname"
    label="Comments"
    theme="dark-blue"
    crossorigin="anonymous"
    async
  ></script>
{:else}
  <script
    src="https://utteranc.es/client.js"
    repo="elianiva/elianiva.me"
    issue-term="pathname"
    label="Comments"
    theme="github-light"
    crossorigin="anonymous"
    async
  ></script>
{/if}
```

**Comment by Himujjal** [comment]
Done merging. I forgot about this. Sorry for the delay. Out of station

**Comment by elianiva** [comment]
no worries, thanks for merging :)

**Pull request merged**
